# Generated by Django 3.1 on 2020-09-01 23:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tweet',
            new_name='Tweet_Model',
        ),
    ]
