# Generated by Django 3.1.1 on 2020-09-03 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet_model',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
