# Generated by Django 3.1.1 on 2020-09-04 20:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0001_initial'),
        ('tweet', '0002_tweet_model_time_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tweet_Model',
            new_name='Tweet',
        ),
    ]
